apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: nlb-gateway-firewall
spec:
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  ingress:
    - fromCIDRSet: 
        - cidr: 78.152.233.215/32 # Zaza
    - fromEntities:
        - cluster
  egress:
    - toEntities:
        - all
