apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: nlb-gateway-firewall
spec:
  egress:
  - toEntities:
    - all
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  ingress:
  - fromCIDRSet:
    - cidr: 109.77.122.188/32
    - cidr: 10.0.20.105/32
  - fromEntities:
    - cluster
