apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: nlb-gateway-firewall
spec:
  egress:
  - toEntities:
    - all
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  ingress:
  - fromCIDRSet:
    - cidr: 109.78.25.44/32
  - fromEntities:
    - cluster
